sudo: required
services:
  - docker

before_install: 
  - docker build -t harmsa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harmsa/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "docker-react-env"
  edge: true
  bucket_name: "elasticbeanstalk-us-west-2-300276692915"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY
